const Amplify = require('@aws-amplify/api').default;
const API = require('@aws-amplify/api').API;
const graphqlOperation = require('@aws-amplify/api').graphqlOperation;

const aws_exports = require('./exports').awsmobile;

const updateConfirmedUserCount =
  require('./graphql/mutations').updateConfirmedUserCount;

const updateUser = require('./graphql/mutations').updateUser;

const getTotalConfirmedUserCount = require('./utils').default;

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

Amplify.configure(aws_exports);

exports.handler = async (event, context, callback) => {
  // const totalUser = await getTotalConfirmedUserCount();
  const totalUser = 100;

  const status = event.request.userAttributes['cognito:user_status'];
  const phone_verified = event.request.userAttributes['phone_number_verified'];
  const email_verified = event.request.userAttributes['email_verified'];
  const phone = event.request.userAttributes.phone_number;
  try {
    const result = await API.graphql(
      graphqlOperation(updateUser, {
        input: {
          id: phone,
          userStatus: status,
          phone_verified: phone_verified,
          email_verified: email_verified,
        },
      })
    );
  } catch (err) {
    console.log(err, '----');
  }

  try {
    const result = await API.graphql(
      graphqlOperation(updateConfirmedUserCount, {
        input: {
          id: '1e26b361-6a39-4345-82bb-0d7775e0d260',
          confirmedUsers: totalUser,
        },
      })
    );
    console.log('Successfully Updated');
    callback(null, event);
  } catch (err) {
    console.log(err);
    callback(null, event);
  }
};
