name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk

  cupertino_icons: ^1.0.2

  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  http: ^0.13.1
  freezed: ^1.1.1
  shared_preferences: ^2.0.5
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.1
  shimmer: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2

  webview_flutter: ^3.0.0
  flutter_html: ^3.0.0-alpha.2
  share: ^2.0.1
  photo_view: ^0.13.0
  package_info: ^2.0.0
  firebase_core: ^1.21.0
  firebase_messaging: ^12.0.3
  flutter_local_notifications: ^9.8.0+1

  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^4.0.1
  flutter_svg: ^1.0.3
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.0.0
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.0
  geolocator: ^9.0.1
  flutter_typeahead: ^3.1.3
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  nb_utils: ^4.6.16

  amplify_flutter: ^0.6.3
  amplify_core: ^0.6.3
  amplify_api: ^0.6.3
  amplify_auth_cognito: ^0.6.5
  amplify_storage_s3: ^0.6.3
  sms_autofill: ^2.2.0
  khalti_flutter: ^2.1.0
  dart_eval: ^0.3.0
  flutter_js: ^0.5.0+6
  scrollable_positioned_list: ^0.3.2
  cool_dropdown: ^1.4.2
  scroll_to_index: ^3.0.1
  im_stepper: ^1.0.1+1
  status_change: ^2.0.0
  edge_detection: ^1.0.9
  # simple_moment: ^1.1.1
  # timezone: ^0.8.0
  google_ml_kit: ^0.12.0
  camera:
  path_provider: ^2.0.11
  ripple_animation: ^0.0.1+2
  crop_image: ^1.0.2
  provider: ^6.0.3
  get_it: ^7.2.0
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.2.2
  flutter_map: ^2.2.0
  image_picker: ^0.8.5+3
  photo_manager: ^2.2.1
  soundpool: ^2.3.0
  loading_animation_widget: ^1.2.0+3
  flutter_image_compress: ^1.1.2
  animated_text_kit: ^4.2.2
  curved_navigation_bar: ^1.0.3
  bottom_bar_page_transition: ^2.0.0
  floating_bubbles: ^2.2.0
  flutter_phone_direct_caller: ^2.1.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/sounds/
    - assets/ml/
    - assets/data/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
