/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

exports.awsmobile = {
  aws_project_region: 'ap-southeast-1',
  aws_appsync_graphqlEndpoint:
    'https://vtlfouhqw5b7hpngywcyqo66pm.appsync-api.ap-southeast-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-southeast-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-zpgkaexm4bhcxnds2dstfqpspu',
  aws_cloud_logic_custom: [
    {
      name: 'kachuwaSendMail',
      endpoint:
        'https://7prtftrvcc.execute-api.ap-southeast-1.amazonaws.com/kachuwa',
      region: 'ap-southeast-1',
    },
    {
      name: 'activeApi',
      endpoint:
        'https://oz133uoo5d.execute-api.ap-southeast-1.amazonaws.com/kachuwa',
      region: 'ap-southeast-1',
    },
  ],
  aws_cognito_identity_pool_id:
    'ap-southeast-1:0cb60986-c91d-4162-8a65-f78c910ec959',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: 'ap-southeast-1_NnOtLUoOc',
  aws_user_pools_web_client_id: '72lcmo1lco6dkc96j86m0hslua',
  oauth: {},
  aws_cognito_username_attributes: ['PHONE_NUMBER'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'kachuwa202918-kachuwa',
  aws_user_files_s3_bucket_region: 'ap-southeast-1',
};
