const Amplify = require('@aws-amplify/api').default;
const API = require('@aws-amplify/api').API;
const graphqlOperation = require('@aws-amplify/api').graphqlOperation;
const aws_exports = require('./exports').awsmobile;
const createUser = require('./graphql/mutations').createUser;

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

Amplify.configure(aws_exports);

exports.handler = async (event, context, callback) => {
  const userName = event.userName;
  const phone = event.request.userAttributes.phone_number;
  const email = event.request.userAttributes.email;

  try {
    const result = await API.graphql(
      graphqlOperation(createUser, {
        input: {
          id: phone,
          userName,
          phone,
          email,
          userStatus: 'UNCONFIRMED',
          baseType: 'userType',
        },
      })
    );
    console.log('Successfully Updated');
    callback(null, event);
  } catch (err) {
    console.log(err);
    callback(null, event);
  }
};
